apiVersion: v1
kind: Service
metadata:
  name: kg-backend-service
  namespace: knowledge-graph
  labels:
    app: kg-backend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: kg-backend
